// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT-k1FhXl1eSRMMwaxFLog3w_nWh2AEG0',
    appId: '1:267426467053:web:a9fa2d8b4c9f4749f350e4',
    messagingSenderId: '267426467053',
    projectId: 'kanban-board-a6945',
    authDomain: 'kanban-board-a6945.firebaseapp.com',
    storageBucket: 'kanban-board-a6945.firebasestorage.app',
    measurementId: 'G-1WF1LQ24VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASNz8SaptAlm-THRLVd1tVZOPOcqyD4t8',
    appId: '1:267426467053:android:a71604c4fe88620df350e4',
    messagingSenderId: '267426467053',
    projectId: 'kanban-board-a6945',
    storageBucket: 'kanban-board-a6945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXr5Utm_t3FBtYFpo2qo1mPi9LhpmMAY4',
    appId: '1:267426467053:ios:62c39d3e04e880fef350e4',
    messagingSenderId: '267426467053',
    projectId: 'kanban-board-a6945',
    storageBucket: 'kanban-board-a6945.firebasestorage.app',
    iosBundleId: 'com.example.todoAppTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXr5Utm_t3FBtYFpo2qo1mPi9LhpmMAY4',
    appId: '1:267426467053:ios:62c39d3e04e880fef350e4',
    messagingSenderId: '267426467053',
    projectId: 'kanban-board-a6945',
    storageBucket: 'kanban-board-a6945.firebasestorage.app',
    iosBundleId: 'com.example.todoAppTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT-k1FhXl1eSRMMwaxFLog3w_nWh2AEG0',
    appId: '1:267426467053:web:4d64db4e7c6e1349f350e4',
    messagingSenderId: '267426467053',
    projectId: 'kanban-board-a6945',
    authDomain: 'kanban-board-a6945.firebaseapp.com',
    storageBucket: 'kanban-board-a6945.firebasestorage.app',
    measurementId: 'G-8BBQXEL13Q',
  );
}
